---
- name: install nftables packages
  ansible.builtin.package:
    name: nftables
    state: latest

- name: generate nftables config
  ansible.builtin.template:
    src: templates/nftables.conf.j2
    dest: /etc/nftables.conf
  notify: restart nftables

# TODO: run nft -c -f /etc/nftables.conf before restarting to check file

- name: enable nftables service and restart if needed
  ansible.builtin.systemd_service:
    name: "nftables"
    enabled: yes
