---
- name: install nftables packages
  ansible.builtin.package:
    name: nftables
    state: latest

- name: generate nftables config
  ansible.builtin.template:
    src: templates/nftables.conf.j2
    dest: /etc/nftables.conf
  notify: check and restart nftables
