---
- name: restart nftables
  ansible.builtin.systemd_service:
    name: nftables
    state: restarted

- name: restart wg-quick
  ansible.builtin.systemd_service:
    name: "wg-quick@{{ net_wg_ifname }}"
    state: restarted
  notify: restart nftables
